apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
      - name: {{ .Values.name}}
        image: {{ .Values.image.name }}: {{ .Values.image.tag }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
